spring:
  application:
    name: taoAPI-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://sh-cdb-mf5lif48.sql.tencentcdb.com:63782/taoapi?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://182.43.17.29:3306/taoapi?useSSL=false&serverTimezone=UTC
    username: root
    password: 2210084657wt
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session 失效时间（分钟）
  session:
    timeout: 86400
    store-type: redis
  redis:
    host: 182.43.17.29
    port: 6379
#    password: 2210084657wt!
#    username: tao
  # redis 配置
#  redis:
#    cluster:
#      nodes:
#        - 192.168.5.128:6387
#        - 192.168.5.128:6388
#        - 192.168.5.128:6389
#        - 192.168.5.128:6397
#        - 192.168.5.128:6398
#        - 192.168.5.128:6399
  boot:
    admin:
      client:
        url: http://127.0.0.1:8282


server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
taoapi:
  client:
    access-key: wtacx
    secret-key: wtacx
    uesr-id: '1'

dubbo:
  application:
    logger: slf4j
    name: taoAPI-backend
    qosAcceptForeignIp: true
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos
    address: nacos://81.68.65.206:8848?namespace=7da0574d-304a-4c50-94d4-a93bd5bd09ef
    group: servers

logging:
  file:
    name: /home/jars/taoAPI/logs/backendLog.log


